apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
spec:
  labels:
    azure.workload.identity/use: "true"
  podTemplate:
    serviceAccountName: clickhouse-azureblobstorage
    volumes:
      - name: clickhouse-azure-blob-storage-config
        configMap:
          name: clickhouse-azure-blob-storage-config
  containerTemplate:
    volumeMounts:
      - name: clickhouse-azure-blob-storage-config
        mountPath: /etc/clickhouse-server/config.d/azure-blob-storage.xml
        subPath: azure-blob-storage.xml
