apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - azure-workload-identity-resources.yaml

patches:
  - path: clickhouse-cluster-patch.yaml
  - path: clickhouse-archive-views-patch.yaml
  - path: grafana-deployment-patch.yaml
  - path: grafana-audit-pipeline-patch.yaml

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: vector
    version: 0.56.0
    releaseName: vector-aggregator
    valuesFile: values.yaml
    includeCRDs: true
