apiVersion: v1
kind: Secret
metadata:
  labels:
    app: clickhouse-clickhouse
  name: clickhouse-clickhouse
  namespace: vector
stringData:
  cluster-secret: YKbDQR@6vcoYz7LQK!-+oLgTOW2Edbli
  interserver-password: fKmMVL77OfUPNqFyY28TBvAdNdkveD5v
  keeper-identity: clickhouse:imKiDgoWFWUQDTFTNRBn-dt2IOGEeD4F
  management-password: az#2AkQ9NMY+%^djumLnnL-l9OuxBuUa
  named-collections-key: 164445fbf8d4e3f838b14e5e017447ef
type: Opaque
