apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-default-password
type: Opaque
stringData:
  password: clickhouse
---
apiVersion: clickhouse.com/v1alpha1
kind: KeeperCluster
metadata:
  name: clickhouse-keeper
spec:
  replicas: 1
  dataVolumeClaimSpec:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  containerTemplate:
    image:
      repository: clickhouse/clickhouse-keeper
      tag: "25.12"
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1Gi
---
apiVersion: clickhouse.com/v1alpha1
kind: ClickHouseCluster
metadata:
  name: clickhouse
spec:
  shards: 3
  replicas: 1
  keeperClusterRef:
    name: clickhouse-keeper
  dataVolumeClaimSpec:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  containerTemplate:
    image:
      repository: clickhouse/clickhouse-server
      tag: "25.12"
    resources:
      requests:
        cpu: "1"
        memory: 4Gi
      limits:
        cpu: "4"
        memory: 16Gi
  settings:
    defaultUserPassword:
      passwordType: password
      secret:
        name: clickhouse-default-password
        key: password
