apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clickhouse-archive-views.yaml
  - clickhouse-bootstrap.yaml
  - clickhouse-secret.yaml
  - clickhouse.yaml
  - dice-service.yaml
  - grafana-audit-pipeline.yaml
  - grafana.yaml
  - grafana-dashboards.yaml
